services:
  postgres:
    image: "docker.io/postgres"
    container_name: "postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "gochat"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: &pass "password"
    ports:
      - "5432:5432"
    networks:
      - &net "dev"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "512M"
    profiles:
      - "db"
      - "all"

  pgadmin:
    image: "docker.io/dpage/pgadmin4"
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "me@email.com"
      PGADMIN_DEFAULT_PASSWORD: *pass
      PGADMIN_LISTEN_PORT: 80
      #PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      #PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
      #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    ports:
      - "5050:80"
    networks:
      - *net
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "256M"
    profiles:
      - "pgadmin"
      - "all"

networks:
  dev:
    driver: "bridge"
